/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package forca;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        Forca f = new Forca();
        f.play();
    }
}
